version: "3.4"
services:
  dev:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0