version: "3.4"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - migrations_dev_data:/app/migrations
    command: python -m flask run -h 0.0.0.0 -p ${FLASK_PORT}
    depends_on:
      - postgres_dev
    expose:
      - ${FLASK_PORT}
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}

  postgres_dev:
    image: postgres:12.5
    env_file:
      - config/postgres_dev.env
    volumes:
      - postgres_dev_data:/var/lib/postgres/data/
    expose:
      - ${POSTGRES_PORT}

  redis_dev:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
    ports:
      - '5555:5555'

volumes:
  postgres_dev_data:
  migrations_dev_data:
